---
# tasks file for production
- name: ensure tomcat8 is present
  apt: 
    name=tomcat8
    state=present

- name: copy war file between build and production
  synchronize:
   # src: "{{ src_folder }}/hello-1.0.war"
    src: "/home/boxfuse/target/hello-1.0.war"
   # dest: "{{ dest_folder }}/hello.war"
    dest: "/var/lib/tomcat8/webapps/hello.war"
  delegate_to: 84.201.170.139
  notify:
    - restart tomcat
